name: "Push to asset lib"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish new version to asset lib
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Copy over files
        run: |
          cp LICENSE.txt addons/godot-css-theme/LICENSE
          cp README.md addons/godot-css-theme/README.md
      - name: Godot Asset Lib
        uses: deep-entertainment/godot-asset-lib-action@v0.3.0
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        with:
          username: sakkaku13
          password: ${{ secrets.ASSET_STORE_PASSWORD }}
          assetId: 1038
