name: "Test"

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Files
        run: godot --import --headless
      - name: Unit Test
        run: sh scripts/test.sh
        timeout-minutes: 1
